### ISSUE TITLE
[BUILD] Master fails to build at Cortex

### ISSUE THREAD

**Issue by noizfactory** [GafferHQ/dependencies#127]
Hi John,

The dependencies build seems to be failing constantly for me when it hits the cortex build at his point:

```bash
scons install installDoc -j 24 CXX=`which g++` INSTALL_PREFIX=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux INSTALL_DOC_DIR=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/doc/cortex INSTALL_RMANPROCEDURAL_NAME=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/renderMan/procedurals/iePython INSTALL_RMANDISPLAY_NAME=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/renderMan/displayDrivers/ieDisplay INSTALL_PYTHON_DIR=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/python INSTALL_ARNOLDOUTPUTDRIVER_NAME=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/arnold/plugins/ieOutputDriver.so INSTALL_IECORE_OPS='' PYTHON_CONFIG=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/bin/python-config BOOST_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include/boost LIBPATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/lib BOOST_LIB_SUFFIX='' OPENEXR_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include OIIO_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include OSL_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include BLOSC_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include FREETYPE_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include/freetype2 WITH_GL=1 GLEW_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include/GL RMAN_ROOT=$RMAN_ROOT NUKE_ROOT= ARNOLD_ROOT=$ARNOLD_ROOT APPLESEED_ROOT=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/appleseed APPLESEED_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/appleseed/include APPLESEED_LIB_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/appleseed/lib ENV_VARS_TO_IMPORT=LD_LIBRARY_PATH OPTIONS='' SAVE_OPTIONS=gaffer.options
[?1034hscons: Reading SConscript files ...
Checking for C++ header file boost/version.hpp... yes
Checking for C++ library boost_iostreams... yes
Checking for C++ library Iex... yes
Checking for C++ library tbb... yes
Checking for C++ library blosc... yes
ERROR : Error running "/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/bin/python-config".
/bin/sh: /repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/bin/python-config: /repo/oss/: bad interpreter: No such file or directory
Traceback (most recent call last):
  File "./build/build.py", line 166, in <module>
    __buildProject( args.project, args.buildDir )
  File "./build/build.py", line 144, in __buildProject
    subprocess.check_call( command, shell = True, env = environment )
  File "/opt/rh/python27/root/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'scons install installDoc -j 24 CXX=`which g++` INSTALL_PREFIX=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux INSTALL_DOC_DIR=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/doc/cortex INSTALL_RMANPROCEDURAL_NAME=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/renderMan/procedurals/iePython INSTALL_RMANDISPLAY_NAME=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/renderMan/displayDrivers/ieDisplay INSTALL_PYTHON_DIR=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/python INSTALL_ARNOLDOUTPUTDRIVER_NAME=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/arnold/plugins/ieOutputDriver.so INSTALL_IECORE_OPS='' PYTHON_CONFIG=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/bin/python-config BOOST_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include/boost LIBPATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/lib BOOST_LIB_SUFFIX='' OPENEXR_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include OIIO_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include OSL_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include BLOSC_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include FREETYPE_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include/freetype2 WITH_GL=1 GLEW_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/include/GL RMAN_ROOT=$RMAN_ROOT NUKE_ROOT= ARNOLD_ROOT=$ARNOLD_ROOT APPLESEED_ROOT=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/appleseed APPLESEED_INCLUDE_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/appleseed/include APPLESEED_LIB_PATH=/repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/appleseed/lib ENV_VARS_TO_IMPORT=LD_LIBRARY_PATH OPTIONS='' SAVE_OPTIONS=gaffer.options' returned non-zero exit status 1
```
I tried both 0.53.0.0 and the latest master from today and it still always fails at this point. I checked the auto-generated python file /repo/oss/gafferhq/build/gafferDependencies-0.53.0.0-linux/bin/python-config and that seems to have the correct path to the gaffer python version (in the same bin directory) which I can execute independently by itself without any issues.

My build [environment](https://hub.docker.com/r/sachinshrestha/gaffer.buildhost.el6) has been the same for all past builds including the last version 0.52.0.0 so a bit vexed here. Any pointers are much appreciated. 

Cheers,
Sachin

**Comment by noizfactory** [comment]
Never mind. I don't know what the issue actually was but I removed my local git repo and recloned the source, the build now seems to move past cortex successfully.

**Comment by noizfactory** [comment]
For anyone searching for this same issue, this turned out to be an issue of the shebang length limit. My `pwd` was getting too long beyond the buffer limit of 127 characters.
